### ISSUE TITLE
swagger & api & swagger ui

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/swagger-api#5]
# swagger & api & swagger ui

https://www.cnblogs.com/xgqfrms/p/9808520.html

**Comment by xgqfrms** [comment]
# error

> bug

```sh

Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start

```

https://github.com/swagger-api/swagger-node/issues/354

**Comment by xgqfrms** [comment]
# solution

> solution

```sh

$ cd ./api/swagger && swagger validate swagger.yaml

```

![image](https://user-images.githubusercontent.com/29531779/47125731-b27a2e80-d2b7-11e8-89f0-c457d508cec7.png)

***

https://stackoverflow.com/questions/37435400/not-a-valid-parameter-definition-swagger-json

http://23.22.16.221/v2/schema.json#

https://npmdoc.github.io/node-npmdoc-swagger-tools/build/apidoc.html

**Comment by xgqfrms** [comment]
# `-`  & yaml bug

> missing `-` symbol bug

![image](https://user-images.githubusercontent.com/29531779/47126329-a6dc3700-d2ba-11e8-93a8-982c6003a254.png)

**Comment by xgqfrms** [comment]
# Error

![image](https://user-images.githubusercontent.com/7291672/47126618-fa02b980-d2bb-11e8-9601-fbd1406ca7fb.png)

http://localhost:8080/users?user=xgqfrms

```json

{
    "message": "Cannot read property 'value' of undefined"
}

```

http://localhost:8080/users?name=xgqfrms

```json

{
    "message": "Cannot read property 'value' of undefined"
}

```

# OK

![image](https://user-images.githubusercontent.com/7291672/47127020-e8221600-d2bd-11e8-8cad-1b1574add486.png)

http://127.0.0.1:8080/hello?name=xgqfrms

```json

{
    "message": "Hello, xgqfrms!"
}

```

**Comment by xgqfrms** [comment]
https://swagger.io/
https://swagger.io/solutions/api-documentation/

http://swagger.io/v2/schema.json
https://swagger.io/v2/schema.json

**Comment by xgqfrms** [comment]
# OK

> object

![image](https://user-images.githubusercontent.com/7291672/47127450-b6aa4a00-d2bf-11e8-89be-eaeb22cee642.png)

# Error

> undefined ??? in-valid

![image](https://user-images.githubusercontent.com/7291672/47127347-587d6700-d2bf-11e8-85cc-10f3d0d15ba7.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/47127532-199be100-d2c0-11e8-904e-7a2ea08a530a.png)
![image](https://user-images.githubusercontent.com/7291672/47127537-20c2ef00-d2c0-11e8-859f-3ff0ec208a4e.png)

![image](https://user-images.githubusercontent.com/7291672/47127588-54057e00-d2c0-11e8-9123-4b58784c7fcb.png)

# Error: Response validation failed: failed schema validation

https://github.com/swagger-api

**Comment by xgqfrms** [comment]
https://github.com/swagger-api/swagger-js
https://github.com/swagger-api/swagger-samples

https://github.com/swagger-api/swagger-node

**Comment by xgqfrms** [comment]
# bug ???

https://github.com/swagger-api/swagger-node/issues/578

**Comment by xgqfrms** [comment]
# solution

> why ???

![image](https://user-images.githubusercontent.com/7291672/47128959-055ae280-d2c6-11e8-9856-8b36cabd05c1.png)

> modify config `default.yaml`

```yaml

   validateResponse: false

```

```yaml
# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [api/mocks]
      controllersDirs: [api/controllers]

    _swagger_validate:
      name: swagger_validator
      validateResponse: false
      # validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...

```
